### ISSUE TITLE
UX/UI incorrect display on 5.5" smartphones (Android 7.0)

### ISSUE THREAD

**Issue by Sami32** [cinnabarhorse/yieldhero#1]
![Screenshot_2020-05-19-14-53-50-496_io metamask](https://user-images.githubusercontent.com/18471069/82329229-473b9580-99e1-11ea-96ed-44fa36f2d631.jpg)
![Screenshot_2020-05-19-14-54-13-193_io metamask](https://user-images.githubusercontent.com/18471069/82329242-4b67b300-99e1-11ea-9baa-6a2908b69d26.jpg)

It doesn't look easily readable from a mobile using MetaMask App.

**Comment by cinnabarhorse** [comment]
Hey this is actually not YieldHero, it's pools.balancer.exchange. I will close this as it's not directly to YieldHero, but will also inform the Balancer team.

Congrats on being the first issue on YieldHero!

**Comment by Sami32** [comment]
Oups...sorry for the noise.
Yes i just tested YieldHero today ;)
